# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  Glad_config = debug
  glm_config = debug
  Jukcraft_config = debug

else ifeq ($(config),beta)
  GLFW_config = beta
  Glad_config = beta
  glm_config = beta
  Jukcraft_config = beta

else ifeq ($(config),release)
  GLFW_config = release
  Glad_config = release
  glm_config = release
  Jukcraft_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW Glad glm Jukcraft

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C vendor/glfw -f Makefile config=$(GLFW_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C vendor/glad -f Makefile config=$(Glad_config)
endif

glm:
ifneq (,$(glm_config))
	@echo "==== Building glm ($(glm_config)) ===="
	@${MAKE} --no-print-directory -C vendor/glm -f Makefile config=$(glm_config)
endif

Jukcraft: GLFW Glad
ifneq (,$(Jukcraft_config))
	@echo "==== Building Jukcraft ($(Jukcraft_config)) ===="
	@${MAKE} --no-print-directory -C Jukcraft -f Makefile config=$(Jukcraft_config)
endif

clean:
	@${MAKE} --no-print-directory -C vendor/glfw -f Makefile clean
	@${MAKE} --no-print-directory -C vendor/glad -f Makefile clean
	@${MAKE} --no-print-directory -C vendor/glm -f Makefile clean
	@${MAKE} --no-print-directory -C Jukcraft -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  beta"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   Glad"
	@echo "   glm"
	@echo "   Jukcraft"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"