# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  Glad_config = debug
  MinecraftClone_config = debug
endif
ifeq ($(config),beta)
  GLFW_config = beta
  Glad_config = beta
  MinecraftClone_config = beta
endif
ifeq ($(config),release)
  GLFW_config = release
  Glad_config = release
  MinecraftClone_config = release
endif

PROJECTS := GLFW Glad MinecraftClone

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C vendor/glfw -f Makefile config=$(GLFW_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C vendor/glad -f Makefile config=$(Glad_config)
endif

MinecraftClone: GLFW Glad
ifneq (,$(MinecraftClone_config))
	@echo "==== Building MinecraftClone ($(MinecraftClone_config)) ===="
	@${MAKE} --no-print-directory -C MinecraftClone -f Makefile config=$(MinecraftClone_config)
endif

clean:
	@${MAKE} --no-print-directory -C vendor/glfw -f Makefile clean
	@${MAKE} --no-print-directory -C vendor/glad -f Makefile clean
	@${MAKE} --no-print-directory -C MinecraftClone -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  beta"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   Glad"
	@echo "   MinecraftClone"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"